# Generated by Django 4.2.1 on 2023-05-09 15:36

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("New Arrival", "New Arrival"),
                            ("Most Popular", "Most Popular"),
                            ("Trending", "Trending"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Moving", "Moving"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=9,
                    ),
                ),
                ("operators", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=50)),
                ("distance", models.CharField(max_length=10)),
                ("start_date", models.DateTimeField()),
                ("est_delivery_due", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrimaryUser",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="profile_image/")),
                ("phone_no", models.BigIntegerField(null=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=("auth.user",),
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("expiry_date", models.DateField()),
                ("units_in_stock", models.IntegerField()),
                ("units_sold", models.IntegerField(null=True)),
                ("image", models.ImageField(null=True, upload_to="product_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Management.category",
                    ),
                ),
            ],
        ),
    ]
