# Generated by Django 4.2.1 on 2023-05-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0003_category_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="media/product_images"),
        ),
    ]
