# Generated by Django 4.2.1 on 2023-05-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="units_sold",
            field=models.IntegerField(null=True),
        ),
    ]
