# Generated by Django 4.2.1 on 2023-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0005_product_units_sold"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Moving", "Moving"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=9,
                    ),
                ),
                ("operators", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=50)),
                ("distance", models.CharField(max_length=10)),
                ("start_date", models.DateTimeField()),
                ("est_delivery_due", models.DateTimeField()),
            ],
        ),
    ]
