# Generated by Django 4.2.1 on 2023-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0006_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="media/product_images"),
        ),
    ]
