# Generated by Django 4.1.1 on 2023-05-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0009_alter_primaryuser_profile_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="primaryuser", old_name="profile_img", new_name="prof_img",
        ),
    ]
