# Generated by Django 4.1.1 on 2023-05-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Management", "0010_rename_profile_img_primaryuser_prof_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="primaryuser", old_name="prof_img", new_name="image",
        ),
    ]
